Update setup script to also setup nvim links

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -50,14 +50,19 @@ install_plugins() {
 }
 
 install() {
-  if [[ -e "$TARGET/.vimrc" || -e "$TARGET/.vim" ]]; then
-    echo "ERROR: '$TARGET/.vim' and/or '$TARGET/.vimrc' already exist."
-    exit 1
-  fi
+  local must_not_exist=("$TARGET/.vimrc" "$TARGET/.vim" "$TARGET/.config/nvim")
+  for f in $must_not_exist; do
+    if [[ -e "$f" || -L "$f" ]]; then
+      echo "ERROR: '$f' already exists"
+      exit 1
+    fi
+  done
 
   mkdir -p "$SOURCE/vim/swp"
+  ln -s "$SOURCE/vim"   "$TARGET/.vim"
   ln -s "$SOURCE/vimrc" "$TARGET/.vimrc"
-  ln -s "$SOURCE/vim" "$TARGET/.vim"
+  ln -s "$SOURCE/vim"   "$TARGET/.config/nvim"
+  ln -s "$SOURCE/vimrc" "$TARGET/.config/nvim/init.vim"
 
   install_plugins false
   patch "$PLUGINS/LaTeX-Box/ftplugin/latex-box/common.vim" < "$SOURCE/latexbox.patch"
